import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:papra_android/features/offline/backup_decoder.dart';
import 'package:papra_android/features/offline/offline_models.dart';

/// End-to-end verification against a fixture generated by the fork's own
/// server code (`papra/scripts/make-backup-fixture.ts`), so the app decoder
/// is proven compatible with the real producer of `.papra-backup` files.
void main() {
  const kek = 'a1b2c3d4a1b2c3d4a1b2c3d4a1b2c3d4a1b2c3d4a1b2c3d4a1b2c3d4a1b2c3d4';

  late Directory tempDir;

  setUp(() {
    tempDir = Directory.systemTemp.createTempSync('real_fixture_test');
  });

  tearDown(() {
    tempDir.deleteSync(recursive: true);
  });

  test('imports a backup produced by the actual server', () async {
    final source = File('test/fixtures/real.papra-backup');
    expect(await source.exists(), isTrue, reason: 'fixture missing');

    final manifest = await extractBackupToDirectory(
      sourcePath: source.path,
      hexKek: kek,
      targetDir: '${tempDir.path}/snapshot',
    );

    final parsed = OfflineManifest.fromJson(manifest);
    expect(parsed.organizationId, 'org-real-001');
    expect(parsed.schemaVersion, 2);
    expect(parsed.documents.length, 2);

    // Document with folder path + tags decodes fully.
    final invoice = parsed.documents[0];
    expect(invoice.id, 'doc-1111');
    expect(invoice.name, 'Invoice January');
    expect(invoice.originalName, 'invoice-january.pdf');
    expect(invoice.notes, 'Paid via bank transfer.');
    expect(invoice.folderPath, ['Finance', '2026']);
    expect(invoice.tags.map((t) => t.name), ['invoice', '2026']);

    // Root-level document (null folderPath) lands at the root.
    final rootDoc = parsed.documents[1];
    expect(rootDoc.folderPath, isEmpty);
    expect(rootDoc.tags, isEmpty);

    // Extracted originals match what the server packed.
    final pdf = File('${tempDir.path}/snapshot/files/doc-1111-invoice-january.pdf');
    expect(await pdf.exists(), isTrue);
    expect(await pdf.readAsBytes(), [37, 80, 68, 70, 45, 49, 46, 55]); // %PDF-1.7

    final txt = File('${tempDir.path}/snapshot/files/doc-2222-root-doc.txt');
    expect(await txt.readAsString(), 'hello from the real server');
  });

  test('OfflineManifest round-trips through toJson for snapshot storage', () async {
    final raw = await extractBackupToDirectory(
      sourcePath: File('test/fixtures/real.papra-backup').path,
      hexKek: kek,
      targetDir: '${tempDir.path}/snapshot2',
    );
    final parsed = OfflineManifest.fromJson(raw);
    final reencoded = jsonEncode(parsed.toJson());
    final reparsed = OfflineManifest.tryParse(reencoded);

    expect(reparsed, isNotNull);
    expect(reparsed!.documents.length, 2);
    expect(reparsed.documents[0].folderPath, ['Finance', '2026']);
    expect(reparsed.documents[0].tags.first.color, '#1e88e5');
  });
}
